import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  Workflow,
  ShoppingCart,
  Menu,
  Filter,
  ChevronDown,
  ChevronUp,
  Car,
  Camera,
  CloudLightning,
  Box,
  Truck,
  X
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  shoppingCart: ShoppingCart,
  menu: Menu,
  filter: Filter,
  chevronDownRadix: ChevronDown,
  chevronUpRadix: ChevronUp,
  engine: Car,
  suspension: Camera,
  brakes: Circle,
  electrical: CloudLightning,
  body: Box,
  accessories: Car,
  truck: Truck,
};

export {Icons};
