import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  Workflow,
  ShoppingCart,
  Menu,
  Filter,
  ChevronDown,
  ChevronUp,
  Car,
  Box,
  Truck,
  X,
  Eye,
  EyeOff,
  Aperture,
  Zap,
  Gift, // Added Gift icon
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  shoppingCart: ShoppingCart,
  menu: Menu,
  filter: Filter,
  chevronDownRadix: ChevronDown,
  chevronUpRadix: ChevronUp,
  car: Car, // Changed 'engine' key to 'car' to match import
  suspension: Zap, // Reverted to Zap as Suspension is not valid
  brakes: Circle,
  electrical: Zap,
  body: Box,
  accessories: Gift, // Using Gift for accessories
  truck: Truck,
  eye: Eye,
  eyeOff: EyeOff,
  aperture: Aperture,
  zap: Zap,
};

export {Icons};
